### ISSUE TITLE
Lambda handler is always set to `datadog_lambda.handler.handler` for `python` runtime

### ISSUE THREAD

**Issue by xhensiladoda** [DataDog/terraform-aws-lambda-datadog#19] opened 2024-10-07 15:42 UTC
Hello,

I am using this module in order to send Lambda logs to DataDog and I can see that if we put `runtime = "python3.9"` then the handler is set to `datadog_lambda.handler.handler`.

Checking the code this seems to come from [this line](https://github.com/DataDog/terraform-aws-lambda-datadog/blob/8fc4541ac7ef8711a7728fd922f6e01de18bd150/main.tf#L28) and [this line](https://github.com/DataDog/terraform-aws-lambda-datadog/blob/8fc4541ac7ef8711a7728fd922f6e01de18bd150/main.tf#L81):

```terraform
  runtime_base_handler_map = {
    dotnet = var.handler
    java   = var.handler
    nodejs = "/opt/nodejs/node_modules/datadog-lambda-js/handler.handler"
    python = "datadog_lambda.handler.handler"
  }

  handler = lookup(local.runtime_base_handler_map, local.runtime_base, var.handler)
```

This is the output of our Terraform plan diff:
```
# module.dev_event_ingestion.module.lambda-datadog.aws_lambda_function.this will be updated in-place
  # (moved from module.dev_event_ingestion.aws_lambda_function.storage_hub_s3_data_raw_ingestion)
  ~ resource "aws_lambda_function" "this" {
      ~ handler                        = "storage_hub-s3-lambda.lambda_handler" -> "datadog_lambda.handler.handler"
        id                             = "dev-storage-hub-s3-data-dev-raw-ingestion"
       ...
    }
```

Can we use this one instead on setting the value of the handler?
```terraform
handler = coalesce(var.handler, lookup(local.runtime_base_handler_map, local.runtime_base))
```

Is there any reason for this behavior? Can't we customize the name of the handler? Am I missing sth on how the module works?
Thanks in advance for your insights 🙏

**Comment by duncanpharvey** [comment] 2024-10-07 18:45
Hi @xhensiladoda!

Renaming the handler to `datadog_lambda.handler.handler` for Python Lambda functions is the intended behavior of this module. The original handler is assigned to the `DD_LAMBDA_HANDLER` environment variable and is called in the [Datadog Lambda Library for Python](https://github.com/DataDog/datadog-lambda-python), which is added as a Lambda Layer by this module.

**Closed** 2024-10-08 12:50 UTC
